"""A nose-down parking stance for ATLAS: the rear legs stay where the landing stand puts them, the front legs
are shortened so the aircraft rests at ``--pitch`` (default -16 deg, nose down). PX4 then has to pivot it about
the rear feet up to the hover pitch before it can lift off, which is the manoeuvre scenarios/pivot_stab.json
flies.

    python scripts/atlas_pivot_stance.py --src airframes/atlas_phase01_best.json --pitch -16 --out airframes/atlas_pivot16.json
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import numpy as np

from airframe_designer.dynamics.quaternion import q_from_euler, q_to_rotmat
from airframe_designer.geometry.gear import Leg

G = 9.80665


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="airframes/atlas_phase01_best.json")
    ap.add_argument("--pitch", type=float, default=-16.0, help="parked pitch, deg nose-up (negative = nose down)")
    ap.add_argument("--out", default="airframes/atlas_pivot16.json")
    ap.add_argument("--km", type=float, default=-0.004,
                    help="reaction-torque coefficient for every rotor (the source file carries an unmeasured -0.01, "
                         "beyond what the aircraft can fly with; every validated flight used -0.004)")
    a = ap.parse_args()
    d = json.loads(Path(a.src).read_text())
    for r in d["rotors"]:
        r["km"] = a.km
    R = q_to_rotmat(q_from_euler(0.0, math.radians(a.pitch), 0.0))
    legs = [Leg.from_dict(l) for l in d["legs"]]
    rear = [l for l in legs if l.attach[0] < 0]
    front = [l for l in legs if l.attach[0] >= 0]
    down = lambda p: float((R @ np.asarray(p, float))[2])
    ground = max(down(l.foot()) for l in rear)          # the rear feet define the ground plane
    for l in front:
        a0 = np.asarray(l.attach, float)
        u = l.direction()
        L = (ground - down(a0)) / down(u)
        old = l.length
        l.length = round(float(L), 4)
        print(f"{l.name}: length {old:.3f} -> {l.length:.3f} m")
    # statics in the parked stance: where the CG sits between the feet, and what the front motors must lift
    cg = np.asarray(d["mass"]["cg"], float)
    m = float(d["mass"].get("mass") or d["mass"].get("total") or 0.0)
    feet = {l.name: R @ (np.asarray(l.foot(), float) - cg) for l in legs}
    rear_x = float(np.mean([feet[l.name][0] for l in rear]))
    front_x = float(np.mean([feet[l.name][0] for l in front]))
    front_share = (-rear_x) / max(1e-6, front_x - rear_x)      # fraction of the weight on the front pair
    # The front legs carry most of the weight here (the CG sits just behind the front feet): size them for the
    # 20 mm static sink the stand was designed with, or the nose sags several degrees further than asked.
    for l in front:
        w = front_share * m * G / 2.0
        l.stiffness = round(w / 0.02, 1)
        l.damping = round(2.0 * 0.8 * math.sqrt(l.stiffness * front_share * m / 2.0), 1)
    d["legs"] = [l.to_dict() for l in legs]
    d["landed_pitch_deg"] = a.pitch
    d["name"] = Path(a.out).stem.upper()
    d["notes"] = (f"{d['name']}: {Path(a.src).name} parked nose-down at {a.pitch:g} deg on shortened front legs "
                  f"(rear legs unchanged), every rotor km set to {a.km:g}. Generated by scripts/atlas_pivot_stance.py for the pivot-and-hover test.")
    Path(a.out).write_text(json.dumps(d, indent=2))
    print("parked at", a.pitch, "deg: feet relative to the CG in the landed frame (x fwd, z down):")
    for k, v in feet.items():
        print(f"  {k}: x={v[0]:+.3f} z={v[2]:+.3f}")
    print(f"CG is {-rear_x:.3f} m ahead of the rear feet -> weight moment {m * G * -rear_x:.1f} Nm about the pivot; "
          f"front legs carry {100 * front_share:.0f}% of the weight (k={front[0].stiffness} N/m)")
    for i, r in enumerate(d["rotors"]):
        if r["pos"][0] > 0:
            p = R @ (np.asarray(r["pos"], float) - cg)
            print(f"  front rotor {i + 1} {r['name']}: arm from rear feet {p[0] - rear_x:.3f} m, max thrust {r['max_thrust']} N")
    print("wrote", a.out)


if __name__ == "__main__":
    main()
